jobs:
  - job: BuildWindowsWithSonarCloud
    displayName: Build for Windows\MSBuild With SonarCloud
    pool:
      Default
    variables:
      BUILD_WRAPPER_DOWNLOAD_URL: https://sonarcloud.io/static/cpp/build-wrapper-win-x86.zip
    steps:
      - task: SonarCloudPrepare@1  
        inputs:
          SonarCloud: "Prueba"
          organization: "bpbreinerpacheco0621"
          scannerMode: "CLI"
          configMode: "file"

      
      - task: SonarCloudAnalyze@1
      - task: SonarCloudPublish@1
        inputs:
          pollingTimeoutSec: '300'

